## ======================================================================
## Pipeline for GPDB PL/R GPPKG
## ======================================================================

groups:
- name: RELEASE
  jobs:
    - plr_centos6_release
    - plr_centos7_release
    - plr_centos6_test
    - plr_centos7_test

resources:

# Image Resources

- name: centos-gpdb-dev-6
  type: docker-image
  source:
    repository: pivotaldata/centos-gpdb-dev
    tag: '6-gcc6.2-llvm3.7'

- name: centos-gpdb-dev-7
  type: docker-image
  source:
    repository: pivotaldata/centos-gpdb-dev
    tag: '7-gcc6.2-llvm3.7'

# Github Source Codes

- name: gpdb_src
  type: git
  source:
    branch: {{gpdb-git-branch}}
    uri: {{gpdb-git-remote}}

- name: plr_src
  type: git
  source:
    branch: master
    uri: https://github.com/greenplum-db/plr.git
    tag_filter: 3.*

# centos 7

- name: plr_gpdb_centos7_build
  type: s3
  source:
    bucket: {{pl-bucket-name}}
    region_name: {{aws-region}}
    access_key_id: {{bucket-access-key-id}}
    secret_access_key: {{bucket-secret-access-key}}
    versioned_file: build/gpdb6/plr/centos7/plr-devel.gppkg

- name: plr_gpdb_centos7_release
  type: s3
  source:
    bucket: {{pl-bucket-name}}
    region_name: {{aws-region}}
    access_key_id: {{bucket-access-key-id}}
    secret_access_key: {{bucket-secret-access-key}}
    regexp: release/gpdb6/plr/plr-(.*)-rhel7-x86_64.gppkg

- name: plr_gpdb_centos7_release_candidate
  type: s3
  source:
    bucket: {{pl-bucket-name}}
    region_name: {{aws-region}}
    access_key_id: {{bucket-access-key-id}}
    secret_access_key: {{bucket-secret-access-key}}
    regexp: release_candidate/gpdb6/plr/plr-(.*)-rhel7-x86_64.gppkg

- name: bin_gpdb_centos7
  type: s3
  source:
    bucket: {{bucket-name}}
    region_name: {{aws-region}}
    access_key_id: {{bucket-access-key-id}}
    secret_access_key: {{bucket-secret-access-key}}
    versioned_file: bin_gpdb_centos7/bin_gpdb.tar.gz

# centtos 6

- name: plr_gpdb_centos6_build
  type: s3
  source:
    bucket: {{pl-bucket-name}}
    region_name: {{aws-region}}
    access_key_id: {{bucket-access-key-id}}
    secret_access_key: {{bucket-secret-access-key}}
    versioned_file: build/gpdb6/plr/centos6/plr-devel.gppkg

- name: plr_gpdb_centos6_release
  type: s3
  source:
    bucket: {{pl-bucket-name}}
    region_name: {{aws-region}}
    access_key_id: {{bucket-access-key-id}}
    secret_access_key: {{bucket-secret-access-key}}
    regexp: release/gpdb6/plr/plr-(.*)-rhel6-x86_64.gppkg

- name: plr_gpdb_centos6_release_candidate
  type: s3
  source:
    bucket: {{pl-bucket-name}}
    region_name: {{aws-region}}
    access_key_id: {{bucket-access-key-id}}
    secret_access_key: {{bucket-secret-access-key}}
    regexp: release_candidate/gpdb6/plr/plr-(.*)-rhel6-x86_64.gppkg

- name: bin_gpdb_centos6
  type: s3
  source:
    bucket: {{bucket-name}}
    region_name: {{aws-region}}
    access_key_id: {{bucket-access-key-id}}
    secret_access_key: {{bucket-secret-access-key}}
    versioned_file: bin_gpdb_centos/bin_gpdb.tar.gz

## ======================================================================
## jobs
## ======================================================================
jobs:
- name: plr_centos6_release
  plan:
  - aggregate:
    - get: centos-gpdb-dev-6
    - get: plr_src
      trigger: true
    - get: plr_gpdb_centos6_build
  - task: release_PLR
    file: plr_src/concourse/tasks/release_plr.yml
    image: centos-gpdb-dev-6
    input_mapping:
      bin_plr: plr_gpdb_centos6_build
    output_mapping:
        plr_gppkg: plr_gpdb_centos6_release
    params:
      OSVER: centos6
      GPDBVER: gp6
  - put: plr_gpdb_centos6_release_candidate
    params:
      file: plr_gpdb_centos6_release/plr-*.gppkg

- name: plr_centos7_release
  plan:
  - aggregate:
    - get: centos-gpdb-dev-7
    - get: plr_src
      trigger: true
    - get: plr_gpdb_centos7_build
  - task: release_PLR
    file: plr_src/concourse/tasks/release_plr.yml
    image: centos-gpdb-dev-7
    input_mapping:
      bin_plr: plr_gpdb_centos7_build
    output_mapping:
      plr_gppkg: plr_gpdb_centos7_release
    params:
      OSVER: centos7
      GPDBVER: gp6
  - put: plr_gpdb_centos7_release_candidate
    params:
      file: plr_gpdb_centos7_release/plr-*.gppkg

- name: plr_centos6_test
  plan:
  - aggregate:
    - get: centos-gpdb-dev-6
    - get: plr_src
    - get: plr_gpdb_centos6_release
    - get: bin_gpdb_centos6
      trigger: true
    - get: gpdb_src
  - task: Test_PLR
    file: plr_src/concourse/tasks/test_plr.yml
    image: centos-gpdb-dev-6
    input_mapping:
      bin_gpdb: bin_gpdb_centos6
      bin_plr: plr_gpdb_centos6_release
    params:
      OSVER: centos6
      GPDBVER: gp6

- name: plr_centos7_test
  plan:
  - aggregate:
    - get: centos-gpdb-dev-7
    - get: plr_src
    - get: plr_gpdb_centos7_release
    - get: bin_gpdb_centos7
      trigger: true
    - get: gpdb_src
  - task: Test_PLR
    file: plr_src/concourse/tasks/test_plr.yml
    image: centos-gpdb-dev-7
    input_mapping:
      bin_gpdb: bin_gpdb_centos7
      bin_plr: plr_gpdb_centos7_release
    params:
      OSVER: centos7
      GPDBVER: gp6

