## ======================================================================
## Pipeline for GPDB PL/R GPPKG
## ======================================================================

groups:
- name: GPDB6
  jobs:
    - plr_centos7_build
    - plr_centos6_build
    - plr_centos6_test
    - plr_centos7_test

resource_types:
- name: gcs
  type: docker-image
  source:
    repository: frodenas/gcs-resource

resources:

# Image Resources

- name: centos-gpdb-dev-6
  type: docker-image
  source:
    repository: pivotaldata/centos-gpdb-dev
    tag: '6-gcc6.2-llvm3.7'

- name: centos-gpdb-dev-7
  type: docker-image
  source:
    repository: pivotaldata/centos-gpdb-dev
    tag: '7-gcc6.2-llvm3.7'

# Github Source Codes

- name: gpdb_src
  type: git
  source:
    branch: {{gpdb-git-branch}}
    uri: {{gpdb-git-remote}}

- name: plr_src
  type: git
  source:
    branch: gpdb6
    uri: https://github.com/greenplum-db/plr.git

# centos 7

- name: bin_gpdb_centos7
  type: gcs
  source:
    bucket: ((gcs-bucket-intermediates))
    json_key: ((concourse-gcs-resources-service-account-key))
    versioned_file: gpdb_master/bin_gpdb_centos7/bin_gpdb.tar.gz

- name: plr_gpdb_centos7_build
  type: gcs
  source:
    json_key: {{gcs-read-write-service-account-key}}
    bucket: {{gcs-bucket-intermediates}}
    versioned_file: plr/plr-centos7/gpdb6/plr-devel.gppkg

- name: plr_gpdb_centos6_build
  type: gcs
  source:
    json_key: {{gcs-read-write-service-account-key}}
    bucket: {{gcs-bucket-intermediates}}
    versioned_file: plr/plr-centos6/gpdb6/plr-devel.gppkg

- name: bin_gpdb_centos6
  type: gcs
  source:
    bucket: ((gcs-bucket-intermediates))
    json_key: ((concourse-gcs-resources-service-account-key))
    versioned_file: gpdb_master/bin_gpdb_centos6/bin_gpdb.tar.gz

- name: plr_gpdb_centos7_bin
  type: gcs
  source:
    json_key: {{gcs-read-write-service-account-key}}
    bucket: {{gcs-bucket}}
    regexp: plr/published/gpdb6/plr-rhel7.gppkg

- name: plr_gpdb_centos6_bin
  type: gcs
  source:
    json_key: {{gcs-read-write-service-account-key}}
    bucket: {{gcs-bucket}}
    regexp: plr/published/gpdb6/plr-rhel6.gppkg

## jobs
## ======================================================================

jobs:

# Build PLR GPPKG

- name: plr_centos7_build
  max_in_flight: 3
  plan:
  - aggregate:
    - get: centos-gpdb-dev-7
    - get: plr_src
      trigger: true
    - get: bin_gpdb_centos7
    - get: gpdb_src
      trigger: true
  - aggregate:
    - task: Build_PLR
      file: plr_src/concourse/tasks/build_plr.yml
      image: centos-gpdb-dev-7
      input_mapping:
        bin_gpdb: bin_gpdb_centos7
      output_mapping:
        bin_plr: plr_gpdb_centos7_build
      params:
        OSVER: centos7
        GPDBVER: gp6
  - aggregate:
    - put: plr_gpdb_centos7_build
      params:
        file: plr_gpdb_centos7_build/plr-*.gppkg

- name: plr_centos6_build
  max_in_flight: 3
  plan:
  - aggregate:
    - get: centos-gpdb-dev-6
    - get: plr_src
      trigger: true
    - get: bin_gpdb_centos6
    - get: gpdb_src
      trigger: true
  - aggregate:
    - task: Build_PLR
      file: plr_src/concourse/tasks/build_plr.yml
      image: centos-gpdb-dev-6
      input_mapping:
        bin_gpdb: bin_gpdb_centos6
      output_mapping:
        bin_plr: plr_gpdb_centos6_build
      params:
        OSVER: centos6
        GPDBVER: gp6
  - aggregate:
    - put: plr_gpdb_centos6_build
      params:
        file: plr_gpdb_centos6_build/plr-*.gppkg

# Test PL/R GPPKG

- name: plr_centos6_test
  plan:
  - aggregate:
    - get: centos-gpdb-dev-6
    - get: plr_src
    - get: plr_gpdb_centos6_build
      passed: [plr_centos6_build]
      trigger: true
    - get: bin_gpdb_centos6
    - get: gpdb_src
  - task: Test_PLR
    file: plr_src/concourse/tasks/test_plr.yml
    image: centos-gpdb-dev-6
    input_mapping:
      bin_gpdb: bin_gpdb_centos6
      bin_plr: plr_gpdb_centos6_build
    output_mapping:
      plr_gppkg: plr_gpdb_centos6_bin
    params:
      OSVER: centos6
      GPDBVER: gp6
  - aggregate:
    - put: plr_gpdb_centos6_bin
      params:
        file: plr_gpdb_centos6_bin/plr-rhel6.gppkg 

- name: plr_centos7_test
  plan:
  - aggregate:
    - get: centos-gpdb-dev-7
    - get: plr_src
    - get: plr_gpdb_centos7_build
      passed: [plr_centos7_build]
      trigger: true
    - get: bin_gpdb_centos7
    - get: gpdb_src
  - task: Test_PLR
    file: plr_src/concourse/tasks/test_plr.yml
    image: centos-gpdb-dev-7
    input_mapping:
      bin_gpdb: bin_gpdb_centos7
      bin_plr: plr_gpdb_centos7_build
    output_mapping:
      plr_gppkg: plr_gpdb_centos7_bin
    params:
      OSVER: centos7
      GPDBVER: gp6
  - aggregate:
    - put: plr_gpdb_centos7_bin
      params:
        file: plr_gpdb_centos7_bin/plr-rhel7.gppkg 

